---
- name: Install
  hosts: localhost
  vars:
    repo_uri: "https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH)"
  tasks:
    - name: Install repo
      become: true
      deb822_repository:
        name: nvidia_toolkit
        uris: "{{ repo_uri }}"
        suites: /
        signed_by: https://nvidia.github.io/libnvidia-container/gpgkey
    - name: Update
      become: true
      apt:
        update_cache: true

